//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.ImplantagrafDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleOperacion
    {
        public int Id { get; set; }
        public int OperacionId { get; set; }
        public int ProductoId { get; set; }
        public double Monto { get; set; }
        public int Cantidad { get; set; }
    }
}
