//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.ImplantagrafDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ImplantagrafModelEntities : DbContext
    {
        public ImplantagrafModelEntities()
            : base("name=ImplantagrafModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carrito> Carrito { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<DetalleOperacion> DetalleOperacion { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<FormaPago> FormaPago { get; set; }
        public virtual DbSet<ItemsCarrito> ItemsCarrito { get; set; }
        public virtual DbSet<Localidad> Localidad { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Operacion> Operacion { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<SEG_Bitacora> SEG_Bitacora { get; set; }
        public virtual DbSet<SEG_DVV> SEG_DVV { get; set; }
        public virtual DbSet<SEG_Excepcion> SEG_Excepcion { get; set; }
        public virtual DbSet<SEG_Idioma> SEG_Idioma { get; set; }
        public virtual DbSet<SEG_Perfil> SEG_Perfil { get; set; }
        public virtual DbSet<SEG_Permiso> SEG_Permiso { get; set; }
        public virtual DbSet<SEG_Traductor> SEG_Traductor { get; set; }
        public virtual DbSet<SEG_Usuario> SEG_Usuario { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<TipoOperacion> TipoOperacion { get; set; }
    }
}
