//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.ImplantagrafDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacion
    {
        public int Id { get; set; }
        public int ClienteId { get; set; }
        public System.DateTime FechaOperacion { get; set; }
        public int TipoOperacionId { get; set; }
        public double MontoTotal { get; set; }
        public Nullable<int> Estado { get; set; }
        public int FacturaId { get; set; }
        public long DVH { get; set; }
    }
}
