//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.ImplantagrafDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEG_Traductor
    {
        public string ElementoId { get; set; }
        public string TraduccionESP { get; set; }
        public string TraduccionENG { get; set; }
        public string TraduccionPOR { get; set; }
        public long DVH { get; set; }
    }
}
