//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentacion.Recursos.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar.
        /// </summary>
        public static string BITACORA_FILTROS_BOTON_FILTRAR {
            get {
                return ResourceManager.GetString("BITACORA_FILTROS_BOTON_FILTRAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bitácora del Sistema.
        /// </summary>
        public static string BITACORA_TITULO {
            get {
                return ResourceManager.GetString("BITACORA_TITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtros de Búsqueda.
        /// </summary>
        public static string BITACORA_TITULO_FILTROS {
            get {
                return ResourceManager.GetString("BITACORA_TITULO_FILTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar al Carrito.
        /// </summary>
        public static string BOTON_AGREGAR_CARRITO {
            get {
                return ResourceManager.GetString("BOTON_AGREGAR_CARRITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo.
        /// </summary>
        public static string BOTON_CATALOGO {
            get {
                return ResourceManager.GetString("BOTON_CATALOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar Compra.
        /// </summary>
        public static string BOTON_COMPRAR {
            get {
                return ResourceManager.GetString("BOTON_COMPRAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string BOTON_ENVIAR {
            get {
                return ResourceManager.GetString("BOTON_ENVIAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quitar Producto.
        /// </summary>
        public static string BOTON_QUITAR_PRODUCTO {
            get {
                return ResourceManager.GetString("BOTON_QUITAR_PRODUCTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarme.
        /// </summary>
        public static string BOTON_REGISTRAR {
            get {
                return ResourceManager.GetString("BOTON_REGISTRAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suscribirme.
        /// </summary>
        public static string BOTON_SUSCRIPCION {
            get {
                return ResourceManager.GetString("BOTON_SUSCRIPCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DETALLE.
        /// </summary>
        public static string BOTON_VER {
            get {
                return ResourceManager.GetString("BOTON_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Cambios.
        /// </summary>
        public static string CUENTA_ACTUALIZARDATOS_BOTON_GUARDAR {
            get {
                return ResourceManager.GetString("CUENTA_ACTUALIZARDATOS_BOTON_GUARDAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Datos de Cuenta.
        /// </summary>
        public static string CUENTA_ACTUALIZARDATOS_TITULO {
            get {
                return ResourceManager.GetString("CUENTA_ACTUALIZARDATOS_TITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Datos.
        /// </summary>
        public static string CUENTA_DETALLE_BOTON_ACTUALIZARDATOS {
            get {
                return ResourceManager.GetString("CUENTA_DETALLE_BOTON_ACTUALIZARDATOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de Contacto.
        /// </summary>
        public static string CUENTA_DETALLE_DATOSCONTACTO {
            get {
                return ResourceManager.GetString("CUENTA_DETALLE_DATOSCONTACTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Personales.
        /// </summary>
        public static string CUENTA_DETALLE_DATOSPERSONALES {
            get {
                return ResourceManager.GetString("CUENTA_DETALLE_DATOSPERSONALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Idioma.
        /// </summary>
        public static string CUENTA_DETALLE_IDIOMA {
            get {
                return ResourceManager.GetString("CUENTA_DETALLE_IDIOMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de Mi Cuenta.
        /// </summary>
        public static string CUENTA_DETALLE_TITULO {
            get {
                return ResourceManager.GetString("CUENTA_DETALLE_TITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar Contraseña.
        /// </summary>
        public static string CUENTA_RECUPERAR_PSW_TITULO {
            get {
                return ResourceManager.GetString("CUENTA_RECUPERAR_PSW_TITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción.
        /// </summary>
        public static string ENTIDAD_ACCION {
            get {
                return ResourceManager.GetString("ENTIDAD_ACCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string ENTIDAD_CANTIDAD {
            get {
                return ResourceManager.GetString("ENTIDAD_CANTIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string ENTIDAD_CODIGO {
            get {
                return ResourceManager.GetString("ENTIDAD_CODIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criticidad.
        /// </summary>
        public static string ENTIDAD_CRITICIDAD {
            get {
                return ResourceManager.GetString("ENTIDAD_CRITICIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string ENTIDAD_DESCRIPCION {
            get {
                return ResourceManager.GetString("ENTIDAD_DESCRIPCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string ENTIDAD_FECHA {
            get {
                return ResourceManager.GetString("ENTIDAD_FECHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Fin.
        /// </summary>
        public static string ENTIDAD_FECHA_FIN {
            get {
                return ResourceManager.GetString("ENTIDAD_FECHA_FIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicio.
        /// </summary>
        public static string ENTIDAD_FECHA_INICIO {
            get {
                return ResourceManager.GetString("ENTIDAD_FECHA_INICIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total a Pagar.
        /// </summary>
        public static string ENTIDAD_IMPORTE_TOTAL_PAGAR {
            get {
                return ResourceManager.GetString("ENTIDAD_IMPORTE_TOTAL_PAGAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio Unitario.
        /// </summary>
        public static string ENTIDAD_PRECIO_UNITARIO {
            get {
                return ResourceManager.GetString("ENTIDAD_PRECIO_UNITARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sub-Total.
        /// </summary>
        public static string ENTIDAD_SUBTOTAL {
            get {
                return ResourceManager.GetString("ENTIDAD_SUBTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string ENTIDAD_USUARIO {
            get {
                return ResourceManager.GetString("ENTIDAD_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disculpe, tuvimos un problema. Por favor contacte un administrador..
        /// </summary>
        public static string EXCEPCIONES_INDEX_TITULO {
            get {
                return ResourceManager.GetString("EXCEPCIONES_INDEX_TITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Llená el formulario de abajo y te responderemos a la brevedad..
        /// </summary>
        public static string HOME_CONTACTO_FORMULARIO_LEYENDA {
            get {
                return ResourceManager.GetString("HOME_CONTACTO_FORMULARIO_LEYENDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay muchas maneras de contactarnos, envianos tu opinión o conoce nuestras oficinas comerciales. Encontrá la forma que mejor se adapte a tus tiempos..
        /// </summary>
        public static string HOME_CONTACTO_LEYENDA {
            get {
                return ResourceManager.GetString("HOME_CONTACTO_LEYENDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string HOME_CONTACTO_TITULO {
            get {
                return ResourceManager.GetString("HOME_CONTACTO_TITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contanos tu Opinión!.
        /// </summary>
        public static string HOME_CONTACTO_TITULO_2 {
            get {
                return ResourceManager.GetString("HOME_CONTACTO_TITULO_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horarios.
        /// </summary>
        public static string HOME_CONTACTO_TITULO_HORARIOS {
            get {
                return ResourceManager.GetString("HOME_CONTACTO_TITULO_HORARIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrado.
        /// </summary>
        public static string HOME_CONTACTO_TITULO_HORARIOS_CERRADO {
            get {
                return ResourceManager.GetString("HOME_CONTACTO_TITULO_HORARIOS_CERRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domingos y Feriados.
        /// </summary>
        public static string HOME_CONTACTO_TITULO_HORARIOS_DOMINGOS_FERIADOS {
            get {
                return ResourceManager.GetString("HOME_CONTACTO_TITULO_HORARIOS_DOMINGOS_FERIADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sábados.
        /// </summary>
        public static string HOME_CONTACTO_TITULO_HORARIOS_SABADO {
            get {
                return ResourceManager.GetString("HOME_CONTACTO_TITULO_HORARIOS_SABADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lun - Vie.
        /// </summary>
        public static string HOME_CONTACTO_TITULO_HORARIOS_SEMANA {
            get {
                return ResourceManager.GetString("HOME_CONTACTO_TITULO_HORARIOS_SEMANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estamos en Ramos Mejía.
        /// </summary>
        public static string HOME_CONTACTO_TITULO_MAPA {
            get {
                return ResourceManager.GetString("HOME_CONTACTO_TITULO_MAPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suscribite a nuestro boletín mensual y enterate de las últimas novedades..
        /// </summary>
        public static string HOME_LEYENDA_FOLLETO {
            get {
                return ResourceManager.GetString("HOME_LEYENDA_FOLLETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días.
        /// </summary>
        public static string HOME_LEYENDA_OFERTA_DIAS {
            get {
                return ResourceManager.GetString("HOME_LEYENDA_OFERTA_DIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horas.
        /// </summary>
        public static string HOME_LEYENDA_OFERTA_HORAS {
            get {
                return ResourceManager.GetString("HOME_LEYENDA_OFERTA_HORAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Min.
        /// </summary>
        public static string HOME_LEYENDA_OFERTA_MINUTOS {
            get {
                return ResourceManager.GetString("HOME_LEYENDA_OFERTA_MINUTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seg.
        /// </summary>
        public static string HOME_LEYENDA_OFERTA_SEGUNDOS {
            get {
                return ResourceManager.GetString("HOME_LEYENDA_OFERTA_SEGUNDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IMPRIMIENDO CONFIANZA.
        /// </summary>
        public static string HOME_LEYENDA_PRINCIPAL_1 {
            get {
                return ResourceManager.GetString("HOME_LEYENDA_PRINCIPAL_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXPERTOS EN SERIGRAFÍA.
        /// </summary>
        public static string HOME_LEYENDA_PRINCIPAL_2 {
            get {
                return ResourceManager.GetString("HOME_LEYENDA_PRINCIPAL_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TECNOLOGÍA SUSTENTABLE.
        /// </summary>
        public static string HOME_SERVICIO_ECOLOGIA_LEYENDA_1 {
            get {
                return ResourceManager.GetString("HOME_SERVICIO_ECOLOGIA_LEYENDA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ECOFRIENDLY.
        /// </summary>
        public static string HOME_SERVICIO_ECOLOGIA_LEYENDA_2 {
            get {
                return ResourceManager.GetString("HOME_SERVICIO_ECOLOGIA_LEYENDA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SERVICIO DE ENVÍOS GRATIS.
        /// </summary>
        public static string HOME_SERVICIO_ENVIO_LEYENDA_1 {
            get {
                return ResourceManager.GetString("HOME_SERVICIO_ENVIO_LEYENDA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a logística especializada.
        /// </summary>
        public static string HOME_SERVICIO_ENVIO_LEYENDA_2 {
            get {
                return ResourceManager.GetString("HOME_SERVICIO_ENVIO_LEYENDA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRODUCTOS IMPORTADOS.
        /// </summary>
        public static string HOME_SERVICIO_IMPORTADOS_LEYENDA_1 {
            get {
                return ResourceManager.GetString("HOME_SERVICIO_IMPORTADOS_LEYENDA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a todo el año.
        /// </summary>
        public static string HOME_SERVICIO_IMPORTADOS_LEYENDA_2 {
            get {
                return ResourceManager.GetString("HOME_SERVICIO_IMPORTADOS_LEYENDA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMPRA DESDE DONDE ESTÉS.
        /// </summary>
        public static string HOME_SERVICIO_LUGAR_LEYENDA_1 {
            get {
                return ResourceManager.GetString("HOME_SERVICIO_LUGAR_LEYENDA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a servicio 24 x 7.
        /// </summary>
        public static string HOME_SERVICIO_LUGAR_LEYENDA_2 {
            get {
                return ResourceManager.GetString("HOME_SERVICIO_LUGAR_LEYENDA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MATERIA PRIMA DE PRIMERA CALIDAD.
        /// </summary>
        public static string HOME_SERVICIO_MATERIALES_LEYENDA_1 {
            get {
                return ResourceManager.GetString("HOME_SERVICIO_MATERIALES_LEYENDA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a garantía de fábrica.
        /// </summary>
        public static string HOME_SERVICIO_MATERIALES_LEYENDA_2 {
            get {
                return ResourceManager.GetString("HOME_SERVICIO_MATERIALES_LEYENDA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SERVICIO TÉCNICO ESPECIALIZADO.
        /// </summary>
        public static string HOME_SERVICIO_TECNICO_LEYENDA_1 {
            get {
                return ResourceManager.GetString("HOME_SERVICIO_TECNICO_LEYENDA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mantenimiento preventivo.
        /// </summary>
        public static string HOME_SERVICIO_TECNICO_LEYENDA_2 {
            get {
                return ResourceManager.GetString("HOME_SERVICIO_TECNICO_LEYENDA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONOCÉ NUESTROS SERVICIOS.
        /// </summary>
        public static string HOME_TITULO_BENEFICIOS {
            get {
                return ResourceManager.GetString("HOME_TITULO_BENEFICIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Boletín de Noticias Virtual.
        /// </summary>
        public static string HOME_TITULO_FOLLETO {
            get {
                return ResourceManager.GetString("HOME_TITULO_FOLLETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OFERTA SEMANAL.
        /// </summary>
        public static string HOME_TITULO_OFERTA_SEMANAL {
            get {
                return ResourceManager.GetString("HOME_TITULO_OFERTA_SEMANAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvido su Contraseña?.
        /// </summary>
        public static string LOGIN_OLVIDO_CONTRASEÑA {
            get {
                return ResourceManager.GetString("LOGIN_OLVIDO_CONTRASEÑA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TENGO UNA CUENTA.
        /// </summary>
        public static string LOGIN_TITULO_TENGO_CUENTA {
            get {
                return ResourceManager.GetString("LOGIN_TITULO_TENGO_CUENTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOY USUARIO NUEVO.
        /// </summary>
        public static string LOGIN_TITULO_USUARIO_NUEVO {
            get {
                return ResourceManager.GetString("LOGIN_TITULO_USUARIO_NUEVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bitácora.
        /// </summary>
        public static string LOYOUT_BARRA_BITACORA {
            get {
                return ResourceManager.GetString("LOYOUT_BARRA_BITACORA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catálogo.
        /// </summary>
        public static string LOYOUT_BARRA_CATALOGO {
            get {
                return ResourceManager.GetString("LOYOUT_BARRA_CATALOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        public static string LOYOUT_BARRA_CONTACTO {
            get {
                return ResourceManager.GetString("LOYOUT_BARRA_CONTACTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Cuenta.
        /// </summary>
        public static string LOYOUT_BARRA_CUENTA_INFO {
            get {
                return ResourceManager.GetString("LOYOUT_BARRA_CUENTA_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string LOYOUT_BARRA_CUENTA_INICIAR {
            get {
                return ResourceManager.GetString("LOYOUT_BARRA_CUENTA_INICIAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesión.
        /// </summary>
        public static string LOYOUT_BARRA_CUENTA_SALIR {
            get {
                return ResourceManager.GetString("LOYOUT_BARRA_CUENTA_SALIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alquileres.
        /// </summary>
        public static string LOYOUT_BARRA_MENU_ALQUILERES {
            get {
                return ResourceManager.GetString("LOYOUT_BARRA_MENU_ALQUILERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        public static string LOYOUT_BARRA_MENU_CLIENTES {
            get {
                return ResourceManager.GetString("LOYOUT_BARRA_MENU_CLIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetos de Negocio.
        /// </summary>
        public static string LOYOUT_BARRA_MENU_NEGOCIO {
            get {
                return ResourceManager.GetString("LOYOUT_BARRA_MENU_NEGOCIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string LOYOUT_BARRA_MENU_USUARIOS {
            get {
                return ResourceManager.GetString("LOYOUT_BARRA_MENU_USUARIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas.
        /// </summary>
        public static string LOYOUT_BARRA_MENU_VENTAS {
            get {
                return ResourceManager.GetString("LOYOUT_BARRA_MENU_VENTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Página Principal.
        /// </summary>
        public static string LOYOUT_BARRA_PAGINAPRINCIPAL {
            get {
                return ResourceManager.GetString("LOYOUT_BARRA_PAGINAPRINCIPAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quienes Somos.
        /// </summary>
        public static string LOYOUT_BARRA_QUIENESSOMOS {
            get {
                return ResourceManager.GetString("LOYOUT_BARRA_QUIENESSOMOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta de Usuario.
        /// </summary>
        public static string LOYOUT_MENU_CUENTA {
            get {
                return ResourceManager.GetString("LOYOUT_MENU_CUENTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string LOYOUT_MENU_IDIOMA {
            get {
                return ResourceManager.GetString("LOYOUT_MENU_IDIOMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a nuestro sitio!.
        /// </summary>
        public static string LOYOUT_SALUDO_BIENVENIDA {
            get {
                return ResourceManager.GetString("LOYOUT_SALUDO_BIENVENIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hola.
        /// </summary>
        public static string LOYOUT_SALUDO_BIENVENIDA_USUARIO {
            get {
                return ResourceManager.GetString("LOYOUT_SALUDO_BIENVENIDA_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usted no tiene Productos en el Carrito..
        /// </summary>
        public static string PRODUCTO_CARRITO_LEYENDA_SIN_PRODUCTOS {
            get {
                return ResourceManager.GetString("PRODUCTO_CARRITO_LEYENDA_SIN_PRODUCTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productos en el Carrito.
        /// </summary>
        public static string PRODUCTO_CARRITO_TITULO {
            get {
                return ResourceManager.GetString("PRODUCTO_CARRITO_TITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CATÁLOGO DE MÁQUINAS.
        /// </summary>
        public static string PRODUCTO_CATALOGO_TITULO {
            get {
                return ResourceManager.GetString("PRODUCTO_CATALOGO_TITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FICHA DEL PRODUCTO.
        /// </summary>
        public static string PRODUCTO_DETALLE_TITULO {
            get {
                return ResourceManager.GetString("PRODUCTO_DETALLE_TITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Impresora Automática.
        /// </summary>
        public static string PRODUCTO_IMPRESORA_AUTOMATICA {
            get {
                return ResourceManager.GetString("PRODUCTO_IMPRESORA_AUTOMATICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Impresora Manual.
        /// </summary>
        public static string PRODUCTO_IMPRESORA_MANUAL {
            get {
                return ResourceManager.GetString("PRODUCTO_IMPRESORA_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Impresora Semi-Automática.
        /// </summary>
        public static string PRODUCTO_IMPRESORA_SEMIAUTOMATICA {
            get {
                return ResourceManager.GetString("PRODUCTO_IMPRESORA_SEMIAUTOMATICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Impresora Tampográfica.
        /// </summary>
        public static string PRODUCTO_IMPRESORA_TAMPOGRAFICA {
            get {
                return ResourceManager.GetString("PRODUCTO_IMPRESORA_TAMPOGRAFICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lámpara UV.
        /// </summary>
        public static string PRODUCTO_LAMPARA_UV {
            get {
                return ResourceManager.GetString("PRODUCTO_LAMPARA_UV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Envío Gratis.
        /// </summary>
        public static string PRODUCTO_LEYENDA_ENVIO {
            get {
                return ResourceManager.GetString("PRODUCTO_LEYENDA_ENVIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Túnel de Secado.
        /// </summary>
        public static string PRODUCTO_TUNEL_SECADO {
            get {
                return ResourceManager.GetString("PRODUCTO_TUNEL_SECADO", resourceCulture);
            }
        }
    }
}
